### ISSUE TITLE
add create_app() factory method

### ISSUE THREAD

**Issue by vsudilov** [adsabs/orcid-service#2]
Hi,

Could you please add a `create_app()` function that returns the `app` object? I'd do it myself, but I cloned the repo and the tests are failing. Not sure how the tests passed on travis -- must be something I have misconfigured.

```
======================================================================
FAIL: test_orcid_profile (orcid_service.tests.test_service.TestServices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/httpretty/core.py", line 1029, in wrapper
    return test(*args, **kw)
  File "/home/vagrant/orcid-service/orcid_service/tests/test_service.py", line 80, in test_orcid_profile
    self.assertStatus(r, 201)
  File "/usr/local/lib/python2.7/dist-packages/flask_testing/utils.py", line 229, in assertStatus
    self.assertEqual(response.status_code, status_code, message)
AssertionError: 500 != 201 : HTTP Status 201 expected but got 500
```

Thanks in advance.

**Comment by romanchyla** [comment]
added

not sure why it fails for you: have you run pip install -r dev-requirements.txt?

**Comment by vsudilov** [comment]
Uh, the code doesn't run period..
